from __future__ import annotations

from uuid import UUID, uuid4

from capillary_actions_sdk.models.student_model import (
    MemoryEntry,
    PreferenceSignal,
    WorkingMemoryAssembly,
)
from capillary_actions_sdk.ports.memory import MemoryStorePort
from capillary_actions_sdk.schema.domain_schema import (
    DomainSchema,
    validate_memory_entry,
)


class MemoryCore:
    def __init__(self, schema: DomainSchema, store: MemoryStorePort):
        """Initialize a MemoryCore object with given DomainSchema and MemoryStorePort objects.

        Args:
            schema (DomainSchema)
            store (MemoryStorePort)

        Returns:
            None
        """
        self.schema = schema
        self.store = store

    async def write(self, subject_id: UUID, entry: MemoryEntry) -> MemoryEntry:
        """Validate and store an entry into the MemoryCore object's MemoryStorePort object.

        Args:
            subject_id (UUID): The unique uuid4 assigned to the subject of interest.
            entry (MemoryEntry): The MemoryEntry object storing relevant information.

        Returns:
            The same MemoryEntry object passed into this function.

        Raises:
            ValueError: if the entry's dimension is not declared in the schema.
            ValueError: if the entry's content is not listed in the fields of that entry's dimension.
        """
        validate_memory_entry(entry=entry, schema=self.schema)
        _validate_content_fields(entry=entry, schema=self.schema)
        await self.store.store(subject_id=subject_id, entry=entry)
        return entry

    async def ingest(self, subject_id: UUID, signal: PreferenceSignal) -> MemoryEntry:
        """Ingests a signal into the MemoryCore object for a particular subject.

        Args:
            subject_id (UUID): The unique uuid4 assigned to the subject of interest.
            signal (PreferenceSignal): The PreferenceSignal object storing relevant information.

        Returns:
            A MemoryEntry object generated by the signal provided as an argument.


        Raises:
            ValueError: if the entry's dimension is not declared in the schema.
            ValueError: if the entry's content is not listed in the fields of that entry's dimension.
        """
        entry = MemoryEntry(
            id=uuid4(),
            tier="long_term",
            dimension=signal.payload["dimension"],
            content=signal.payload.get("content", {}),
            metadata={"signal_id": str(signal.id), "source": signal.source},
        )
        return await self.write(subject_id=subject_id, entry=entry)

    async def assemble_working_memory(self, subject_id: UUID) -> WorkingMemoryAssembly:
        """Creates a WorkingMemoryAssembly object containing all the entries for a given subject.

        Args:
            subject_id (UUID): The unique uuid4 assigned to the subject of interest.

        Returns:
            A WorkingMemoryAssembly object, with learner_id=subject_id and entries is a list of entries written to the subject.
        """
        entries = await self.store.get(subject_id=subject_id)
        return WorkingMemoryAssembly(learner_id=subject_id, entries=entries)


def _validate_content_fields(entry: MemoryEntry, schema: DomainSchema) -> None:
    """Validate a memory entry against a domain schema based on the entry's content.

    Raises:
        ValueError: if the entry's content is not listed in the fields of that entry's dimension.
    """
    offending = []
    valid = []
    for field in entry.content.keys():
        if field not in schema.dimension(entry.dimension).fields:
            offending.append(field)
        else:
            valid.append(field)

    if offending:
        raise ValueError(
            f"The following entry keys do not match with the provided schema: {offending}\n"
            f"Valid fields: {valid}"
        )
